I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/sans.rpy", line 17, in script
  File "game/sans.rpy", line 17, in <module>
NameError: name 'process_list' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/sans.rpy", line 17, in script
  File "C:\Users\donov\Downloads\renpy-7.1.1-sdk\renpy\ast.py", line 1760, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\donov\Downloads\renpy-7.1.1-sdk\renpy\python.py", line 1944, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\donov\Downloads\renpy-7.1.1-sdk\renpy\python.py", line 1937, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/sans.rpy", line 17, in <module>
NameError: name 'process_list' is not defined

Windows-8-6.2.9200
Ren'Py 7.1.1.929
Galaxies 0.10.16
Sun Oct 21 12:07:47 2018
